name: Build ZMK Analog Stick Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-dev-arm:3.5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Clean up build dir if exists
        run: |
          rm -rf build

      - name: Initialize west
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: List shield folders for debug
        run: |
          find config/boards/shields -type f

      - name: Build firmware
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble \
            -- -DSHIELD=analog_stick_test \
            
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
